#! /bin/bash

ps -ef | grep 3005 | grep puma
if [ $? -eq 1 ]
then
  echo "Server is down."
  bundle exec puma -t 5:5 -d -p 3005 -e production -S ~/puma -C config/puma.rb
else
  echo "Server running ;)!"
fi
